site_name: MoE Research

nav:
  - Home: index.md
  - Dataset: dataset.md
  - Training: training.md
  - Evaluation: evaluation.md

theme:
  name: material
  features:
    - content.code.copy

docs_dir: wiki
site_dir: docs

repo_url: https://github.com/cxcscmu/MoE-Research
